import { expandOccurrences } from './calendarRecurrence.mjs';

function timestampMillis(value) {
  if (typeof value?.toMillis === 'function') return value.toMillis();
  const date = value instanceof Date ? value : new Date(value);
  return Number.isFinite(date.getTime()) ? date.getTime() : null;
}

function normalizedProjectId(value) {
  return typeof value === 'string' ? value.trim() : '';
}

export function normalizeCalendarRecurrenceInterval(value) {
  return Math.max(1, Math.min(12, Math.floor(Number(value) || 1)));
}

function normalizedRecurrence(value) {
  return {
    frequency: typeof value?.frequency === 'string' ? value.frequency : 'none',
    interval: normalizeCalendarRecurrenceInterval(value?.interval),
    until: typeof value?.until === 'string' ? value.until : '',
  };
}

function sameRecurrence(left, right) {
  const a = normalizedRecurrence(left);
  const b = normalizedRecurrence(right);
  return a.frequency === b.frequency
    && a.interval === b.interval
    && a.until === b.until;
}

export function calendarEventSourceIdentityChanged(current, next) {
  return normalizedProjectId(current?.projectId) !== normalizedProjectId(next?.projectId)
    || timestampMillis(current?.startAt) !== timestampMillis(next?.startAt)
    || timestampMillis(current?.endAt) !== timestampMillis(next?.endAt)
    || Boolean(current?.allDay) !== Boolean(next?.allDay)
    || !sameRecurrence(current?.recurrence, next?.recurrence)
    || current?.visibility !== next?.visibility;
}

export function normalizeCalendarOccurrence(value) {
  if (typeof value !== 'string' || !value.trim() || value.length > 100) return null;
  const date = new Date(value);
  return Number.isFinite(date.getTime()) ? date.toISOString() : null;
}

export function isCanonicalCalendarOccurrence(value) {
  const normalized = normalizeCalendarOccurrence(value);
  return normalized !== null && normalized === value;
}

/**
 * Checks that an occurrence is the exact instant generated by the shared UTC
 * recurrence engine. Approximate time matching is unsafe for billing because
 * two nearby timestamps would become two independently billable item IDs.
 */
export function isCalendarEventOccurrence(event, occurrenceStartAt) {
  const occurrenceIso = normalizeCalendarOccurrence(occurrenceStartAt);
  const seriesStartMs = timestampMillis(event?.startAt);
  if (!occurrenceIso || seriesStartMs == null) return false;
  if ((event?.excludedOccurrenceStarts || []).includes(occurrenceIso)) return false;
  const occurrence = new Date(occurrenceIso);
  const seriesStart = new Date(seriesStartMs);
  const recurrence = normalizedRecurrence(event?.recurrence);

  const { occurrences } = expandOccurrences({
    start: seriesStart,
    frequency: recurrence.frequency,
    interval: recurrence.interval,
    until: recurrence.until
      ? `${recurrence.until}T23:59:59.999Z`
      : null,
    windowStart: occurrence,
    windowEnd: occurrence,
    maxOccurrences: 2,
  });
  return occurrences.some(candidate => candidate.getTime() === occurrence.getTime());
}

export function calendarTimeLogBillingDetails(logs = []) {
  const billed = logs.filter(log => (
    (typeof log?.invoiceId === 'string' && log.invoiceId.trim())
    || log?.billedAt
  ));
  return {
    timeLogCount: logs.length,
    billedTimeLogCount: billed.length,
    billedTimeLogIds: billed.map(log => log.id).filter(Boolean),
    invoiceIds: [...new Set(
      billed
        .map(log => (typeof log.invoiceId === 'string' ? log.invoiceId.trim() : ''))
        .filter(Boolean),
    )].sort(),
  };
}
